### ISSUE TITLE
Group name mismatch

### ISSUE THREAD

**Issue by mnf1980** [mnf1980/SIM#10]
The name of the group remains "public"; even if the trader is in a different group
![3](https://user-images.githubusercontent.com/84329389/210985305-0cda27e2-a530-4220-85f8-d304bc5070ec.PNG)

**Comment by Samiaatieh** [comment]
Done to show group name please check it 

![image](https://user-images.githubusercontent.com/122079188/218032730-6c86f02c-be9c-4052-8971-f193898d5034.png)
