### ISSUE TITLE
system showing a volume on non-traded securities 

### ISSUE THREAD

**Issue by mnf1980** [mnf1980/SIM#15]
Fix some symbols that show volume in the sim, not real (these symbols didn’t trade in the sim), 
(AWNIC, KICO, RAKWCT, UNION…)
![0](https://user-images.githubusercontent.com/84329389/210996946-0f6da67b-6303-4da5-8fd8-648bc23b5aae.PNG)

**Comment by mnf1980** [comment]
this issue is similar to the issue #32

**Comment by mnf1980** [comment]
#32

**Comment by mnf1980** [comment]
in the picture below you will see a volume of 150 contract on ADCBF-0123 but not in the real market and not even traded on the SIM


![27](https://user-images.githubusercontent.com/84329389/213368316-f398c949-13ca-4a99-8bf6-a65549883b80.png)

**Comment by Samiaatieh** [comment]
Done please check it on next day of trading (not today)
