### ISSUE TITLE
Commission issue

### ISSUE THREAD

**Issue by mnf1980** [mnf1980/SIM#17]
the commission is subtracting from the initial margin in short futures.
**the cash block should be 20,000 + 200.21 = 20,200.21**

![15](https://user-images.githubusercontent.com/84329389/210998597-9fb57ebc-22b7-4e87-a714-9e68f8cc3d72.png)

**Comment by Samiaatieh** [comment]
Dear Manaf, 
Done as we agreed i remove cash block from console

**Comment by mnf1980** [comment]
issue is return back. please check 

![image](https://user-images.githubusercontent.com/84329389/226317238-70c6b201-7968-46f8-943e-89bcfa757cff.png)

**Comment by Samiaatieh** [comment]
Done
