### ISSUE TITLE
Sorting market watch table

### ISSUE THREAD

**Issue by mnf1980** [mnf1980/SIM#18]
Market Watch is not sorting alphabetically, or please add the ability to sort by name, price, change, volume, value, etc.

**Comment by Samiaatieh** [comment]
Done please check it and let me know

**Comment by mnf1980** [comment]
sorting by security name is working fine, but others are not working probably.
trying to sort other tabs dont sort them correctly.

**Comment by Samiaatieh** [comment]
Done please check it

**Comment by mnf1980** [comment]
same problem dear 

![image](https://user-images.githubusercontent.com/84329389/225844314-54470b4a-2eb9-47f2-badc-816cee35a3c0.png)

![image](https://user-images.githubusercontent.com/84329389/225844603-76c788e0-6c13-4858-bce0-2b0c3fbb9738.png)

![image](https://user-images.githubusercontent.com/84329389/225844755-44491976-3ea8-45d6-b086-4411bd0d8b0b.png)

**Comment by Samiaatieh** [comment]
Done

**Comment by mnf1980** [comment]
not yet Samia, same issue

**Comment by Samiaatieh** [comment]
More details which column ?!

**Comment by mnf1980** [comment]
all,
only security name is working fine

**Comment by Samiaatieh** [comment]
done
