### ISSUE TITLE
Settlement issue for Future contract

### ISSUE THREAD

**Issue by mnf1980** [mnf1980/SIM#23]
On my account (13) and at 2:45 the system closes all my December positions at the market price.
The correct behavior is to close these positions at the end of the day and at the last settlement price (the closing price of the underlying asset), which is provided by the ADX in the daily Excel sheet.
I still need help understanding the system's current behavior in handling the settlement process.

![41](https://user-images.githubusercontent.com/84329389/211000730-271e0448-ab52-4ee5-b2a6-8153f9b8cca4.PNG)

**Comment by Samiaatieh** [comment]
Please check it today

**Comment by mnf1980** [comment]
same problem
