### ISSUE TITLE
Adding watermark for "statement of account"

### ISSUE THREAD

**Issue by mnf1980** [mnf1980/SIM#27]
Adding "ADX Simulation" as watermark for "statement of account" to prevent using it as real trade statement.

**Comment by Samiaatieh** [comment]
More details or screenshot

**Comment by mnf1980** [comment]
Adding watermark for the statement, like "ADX Simulation"

![25](https://user-images.githubusercontent.com/84329389/213103619-87c8a356-1fe9-48da-bc12-d0c2435b4ec0.png)

**Comment by Samiaatieh** [comment]
As we agreed we will Export on PDF

**Comment by mnf1980** [comment]
ok, sounds good

**Comment by Samiaatieh** [comment]
Done added Export on PDF

**Comment by mnf1980** [comment]
thank you Samia, it is very good.
we still need the watermark inside the pdf to shows the trade as a demo trades/account.

**Comment by Samiaatieh** [comment]
@mnf1980  what you mean showing logo of you company , please send me more details and screenshot

**Comment by mnf1980** [comment]
please change the address to 
"Ground Floor - South Entrance l Landmark Tower Al Hisn ST - Al Markaziyah West - Corniche - Abu Dhabi, UAE, Tel. 971 2 6277777, E-mail. Support@adx.ae

**Comment by mnf1980** [comment]
it is not logo. as we discussed before, add **wathermark** to the exported PDF that clarify it is demo account not real account.

![image](https://user-images.githubusercontent.com/84329389/224268150-880bd024-3782-4c7b-9d91-25478ca39f00.png)

**Comment by Samiaatieh** [comment]
Done , please check it 

![image](https://user-images.githubusercontent.com/122079188/225837528-a51b6ef7-1bbc-44b1-ad90-b30eb126ffdb.png)
