### ISSUE TITLE
Adding new slide has not effect

### ISSUE THREAD

**Issue by mnf1980** [mnf1980/SIM#3]
On the "How To Trade Slides" page in the admin portal, I can't reset to default or even delete the files I uploaded before. 
There is an empty slot on the right side (please refer to the attached picture), which is not working. 
Adding a new slide takes no effect. Please confirm.
![11](https://user-images.githubusercontent.com/84329389/210942232-354697c1-2a3f-4465-8922-4fb4be279852.PNG)

**Comment by Samiaatieh** [comment]
As we agreed please send me the sliders and we will do it to you until we fix this page

**Comment by mnf1980** [comment]
email send,
Please use it to both AR and AR pages.

**Comment by Samiaatieh** [comment]
Done added Sliders on arabic and English
