### ISSUE TITLE
statement of account not showing the correct commission 

### ISSUE THREAD

**Issue by mnf1980** [mnf1980/SIM#35]
Statement of account not showing the correct commission.
The confirmation trade window shows the corrected commission, but the statement is not.

![30](https://user-images.githubusercontent.com/84329389/218435805-42038057-5d89-4d37-8b06-d2e3400bca4c.png)

**Comment by Samiaatieh** [comment]
Done please check it VAT was not showing that why

**Comment by mnf1980** [comment]
Equity side is fixed, **Future side is not** 

![37](https://user-images.githubusercontent.com/84329389/223089096-3764ef62-0c88-49e4-bae2-b41c1ae9efbc.png)

**Comment by Samiaatieh** [comment]
Done setting on market level  Excluded From VAT was checked for ADX DEV
