### ISSUE TITLE
Derivative contract executed @ 2:45 for expiry contract

### ISSUE THREAD

**Issue by mnf1980** [mnf1980/SIM#4]
I put order to sell 25k Aldar share @ 4.60 early in the morning. at 2:45 the system executes the trade at 5.20.
![10](https://user-images.githubusercontent.com/84329389/210980868-ac55d753-b694-4737-94ef-9b2bb99d9b1a.PNG)

**Comment by Samiaatieh** [comment]
Done please check it

**Comment by mnf1980** [comment]
I tried again today, and the same problem occurred.

![16](https://user-images.githubusercontent.com/84329389/211003721-8eef404d-699f-4e78-857f-7f09ed21ff50.PNG)

**Comment by mnf1980** [comment]
**with reference to issue #23** 

The system executes more trades in my account at 2:45 to close the December positions.

**Comment by mnf1980** [comment]
On my account (13) and at 2:45 the system closes all my December positions at the market price.
The correct behavior is to close these positions at the end of the day and at the last settlement price (the closing price of the underlying asset), which is provided by the ADX in the daily Excel sheet.
I still need help understanding the system's current behavior in handling the settlement process.


![41](https://user-images.githubusercontent.com/84329389/211000730-271e0448-ab52-4ee5-b2a6-8153f9b8cca4.PNG)

**Comment by Samiaatieh** [comment]
Fixed for adx market 

for adx derv please send exctly the times for per open,open,perclosed ,closed

**Comment by mnf1980** [comment]
derivatives are trading from 10:00 to 3:00
no pre-open or pre-close

**Comment by mnf1980** [comment]
is there any update on this issue,

**Comment by Samiaatieh** [comment]
@mnf1980 can you check it today,  we make it to be completed at 15:03 at a close price of Underlying LastPrice

**Comment by mnf1980** [comment]
Dear Samia,
please note that you can close the expired contract after 15:00 at **_the closing price of the underlying asset_** (stock).
this is only true at the end of the future contract and only for the expired one.

**Comment by Samiaatieh** [comment]
done as you requested
