### ISSUE TITLE
Arabic Translation

### ISSUE THREAD

**Issue by mnf1980** [mnf1980/SIM#5]
Here is a list of missing translations for the Sim. please check the pictures attached.
![6](https://user-images.githubusercontent.com/84329389/210981830-11dc4a13-94c0-4102-ad43-99314375c1a1.PNG)
![7-1](https://user-images.githubusercontent.com/84329389/210981845-a0fe0e7c-05d2-4054-b29b-113d273aee2a.PNG)
![7-2](https://user-images.githubusercontent.com/84329389/210981848-5da9ebec-75c9-4bd5-897d-15352b47ebd7.PNG)

**Comment by Samiaatieh** [comment]
Done Please check 

![12](https://user-images.githubusercontent.com/122079188/212031163-0c822415-e439-4d08-bac1-49dc93dc3e05.png)

**Comment by mnf1980** [comment]
thanks for the update, view things left please check the pic below:
The **"all"** label is not changing colors when swiched. 


![19](https://user-images.githubusercontent.com/84329389/212034118-1dd9033c-03d1-4c48-b45c-5d905b43c62e.png)
![20](https://user-images.githubusercontent.com/84329389/212034357-77dd969f-0852-4b4e-b85f-afa1414db572.png)

**Comment by mnf1980** [comment]
Check this also

![21](https://user-images.githubusercontent.com/84329389/212037564-19986ec0-9db9-46b4-b882-abc091cbf3b6.png)
![22](https://user-images.githubusercontent.com/84329389/212037568-970b1c47-8af8-48d0-ba39-17898aa0cdc8.png)
![23](https://user-images.githubusercontent.com/84329389/212037574-00e50f03-ae96-4173-8f1f-ba8a62d8c14e.png)

**Comment by Samiaatieh** [comment]
Arabic is already fixed and  you can translate anything by going to System settings > Language  
For Desc on Statement of account we can't change it

**Comment by mnf1980** [comment]
working fine thanks
