### ISSUE TITLE
link issue

### ISSUE THREAD

**Issue by mnf1980** [mnf1980/SIM#6]
The link needs to correct on the "Welcome back" page (after activating a new account)
![1](https://user-images.githubusercontent.com/84329389/210982726-243ec996-64a3-44ec-bf2f-8521328a5337.PNG)

**Comment by Samiaatieh** [comment]
Done Please check it

**Comment by mnf1980** [comment]
the problem still excited

**Comment by Samiaatieh** [comment]
Done please check it

**Comment by mnf1980** [comment]
now it works thank Samia
