### ISSUE TITLE
Text link issue in legal page

### ISSUE THREAD

**Issue by mnf1980** [mnf1980/SIM#7]
After creating and activating an account, the "Legal Disclaimer" page appears, and the text/links are incorrect.
![2](https://user-images.githubusercontent.com/84329389/210983362-96af6a17-aa5e-4729-a72c-93c55839e39d.PNG)

**Comment by mnf1980** [comment]
- the legal page is not showing the "list" format 
- ADX logo is very small, please move it to the top and make it bigger.
- please remove zag trader footer from the page.
- "I AGREE" button is gray out when scrolling down to the end of the page.

![18](https://user-images.githubusercontent.com/84329389/211518805-f80191f7-dd29-4909-904f-4088b5fca6a8.png)

**Comment by Samiaatieh** [comment]
Fixed

**Comment by mnf1980** [comment]
working fine thank you
