### ISSUE TITLE
"Force Activation" will add the new register trader in public group

### ISSUE THREAD

**Issue by mnf1980** [mnf1980/SIM#9]
Choosing a different game on the registration page has no effect (the trader still registers for the public game).

**Comment by Samiaatieh** [comment]
Fixed please check it

**Comment by mnf1980** [comment]
same problem

**Comment by Samiaatieh** [comment]
Done please check it and let me know your feedback

**Comment by mnf1980** [comment]
I registered new user today "faqodahivuc@jollyfree.com" under xyz group but still it is under public.

**Comment by mnf1980** [comment]
ok, I think I find out the problem.
using **"Force Activation"** in the control panel will ignore the group setting when register and put the trader in public group instead.

**Comment by Samiaatieh** [comment]
Fixed please check it
